"""
Answer Leak Validator
---------------------
Detects questions within the SAME exam set that inadvertently reveal
the answer to another question.

Classic example from the project:
  Q1 (assertion_reason): "Paste Special (Ctrl+Shift+V) allows you to paste
      only values…"  ← the shortcut is stated in the stem
  Q2 (standard): "What is the keyboard shortcut for Paste Special?" 
      ← student can answer from Q1 without knowing the topic

Detection strategy
------------------
1. Extract "answer anchors" from each question:
   - Keyboard shortcuts  (Ctrl+X, Shift+F5, Alt+Del …)
   - Acronym expansions  (LAN = Local Area Network, UPI = Unified Payment Interface …)
   - Named facts         (specific numbers, URLs, formulas, file paths)

2. For every other question in the set whose correct answer matches one
   of those anchors, flag it as a potential leak pair.

3. Return (passed, reason) per question — flagged questions are
   regenerated by pipeline.run_quality_validation_pass().

Public API
----------
  validate_answer_leaks(questions) → list[tuple[bool, str]]
    Returns (passed, reason) per question.
    The QUESTION THAT LEAKS is not flagged — the DOWNSTREAM question
    that benefits from the leak is flagged (it should be regenerated
    with a different angle so it doesn't rely on Q1 for the answer).
"""

import re
import logging
from models import Question

logger = logging.getLogger(__name__)

# ── Anchor extractors ──────────────────────────────────────────────────────────

# Keyboard shortcuts: Ctrl+S, Shift+F5, Alt+Del, Ctrl+Shift+V, Win+D …
_SHORTCUT_RE = re.compile(
    r"\b((?:Ctrl|Shift|Alt|Win|Fn|Cmd)(?:\+(?:Ctrl|Shift|Alt|Win|Fn|Cmd))*"
    r"\+[A-Za-z0-9_]+)\b",
    re.IGNORECASE,
)

# Function keys: F1–F12
_FKEY_RE = re.compile(r"\bF([1-9]|1[0-2])\b")

# Acronym definitions: "LAN (Local Area Network)" or "Local Area Network (LAN)"
_ACRONYM_DEFINE_RE = re.compile(
    r"\b([A-Z]{2,6})\s*[\(–-]\s*([A-Za-z][A-Za-z ]{3,40})\)|"
    r"\b([A-Za-z][A-Za-z ]{3,40})\s*[\(–-]\s*([A-Z]{2,6})\b"
)

# Spreadsheet formulas: =SUM(, =MAX(, =AVERAGE( …
_FORMULA_RE = re.compile(r"=([A-Z]{2,12})\s*\(", re.IGNORECASE)

# Specific numbers that are facts: port 80, *99#, 32-bit, 128-bit …
_FACT_NUMBER_RE = re.compile(r"\b(\*?\d+#?(?:-bit)?)\b")

# URL protocols + common scheme facts
_URL_FACT_RE = re.compile(r"\b(https?|ftp|smtp|pop3|imap|tcp/ip)\b", re.IGNORECASE)


def _extract_anchors(text: str) -> set[str]:
    """Pull specific answerable facts out of a text string."""
    anchors: set[str] = set()

    for m in _SHORTCUT_RE.finditer(text):
        anchors.add(m.group(0).upper())

    for m in _FKEY_RE.finditer(text):
        anchors.add(m.group(0).upper())

    for m in _ACRONYM_DEFINE_RE.finditer(text):
        # Both the acronym and the expansion become anchors
        groups = [g.strip() for g in m.groups() if g]
        anchors.update(g.lower() for g in groups if len(g) > 1)

    for m in _FORMULA_RE.finditer(text):
        anchors.add(m.group(1).upper() + "()")

    for m in _FACT_NUMBER_RE.finditer(text):
        val = m.group(1)
        if len(val) >= 2:   # skip trivial single digits
            anchors.add(val.lower())

    for m in _URL_FACT_RE.finditer(text):
        anchors.add(m.group(1).lower())

    return anchors


def _normalise(text: str) -> str:
    return re.sub(r"\s+", " ", text.strip().lower())


# ── Public API ─────────────────────────────────────────────────────────────────

def validate_answer_leaks(questions: list[Question]) -> list[tuple[bool, str]]:
    """
    Scan all questions in the set for answer-leaking pairs.

    For each question Q_i, extract answer anchors from its full text (stem +
    all options + correct answer).  Then check every other question Q_j to
    see if Q_j's correct_answer matches one of Q_i's anchors.

    If it does:
      - Q_j is flagged (it's the question whose answer is leaked BY Q_i).
      - Q_i itself is NOT flagged — it contains valid information; we just
        don't want another question whose answer can be read directly from Q_i.

    Returns (passed, reason) per question — same length as input.
    """
    n = len(questions)
    results: list[tuple[bool, str]] = [(True, "")] * n

    if n < 2:
        return results

    # Pre-compute anchors for every question's FULL TEXT (stem + options)
    question_anchors: list[set[str]] = []
    for q in questions:
        full_text = q.question + " " + " ".join(q.options)
        question_anchors.append(_extract_anchors(full_text))

    leak_pairs = []  # (source_idx, target_idx, anchor, leaked_answer)

    for i in range(n):
        if not question_anchors[i]:
            continue
        for j in range(n):
            if i == j:
                continue
            # Does Q_j's correct answer appear as an anchor in Q_i?
            ca_norm = _normalise(questions[j].correct_answer)
            ca_upper = questions[j].correct_answer.upper().replace(" ", "")
            for anchor in question_anchors[i]:
                anchor_upper = anchor.upper().replace(" ", "")
                if (anchor_upper in ca_upper or ca_upper in anchor_upper
                        or anchor in ca_norm or ca_norm in anchor):
                    # F-keys are 2 chars (F5) but still meaningful; shortcuts are longer
                    if len(anchor) >= 2:
                        leak_pairs.append((i, j, anchor, questions[j].correct_answer))
                        break

    flagged_indices: dict[int, list[str]] = {}
    for source_i, target_j, anchor, leaked_ans in leak_pairs:
        if target_j not in flagged_indices:
            flagged_indices[target_j] = []
        flagged_indices[target_j].append(
            f"Answer '{leaked_ans[:50]}' is revealed by Q{source_i+1} "
            f"(anchor: '{anchor}'). Regenerate with a different angle "
            f"that cannot be answered by reading another question in the set."
        )

    for idx, reasons in flagged_indices.items():
        results[idx] = (False, " | ".join(reasons))
        logger.info(
            f"    ✗ Answer-Leak Q{idx+1}: {results[idx][1][:120]}"
        )

    if flagged_indices:
        logger.info(
            f"  Answer-leak check: {len(flagged_indices)} question(s) flagged "
            f"across {len(leak_pairs)} leak pair(s)"
        )

    return results
